"""Generate the synthetic date-normalisation corpus for the Week 4 lecture notebook.

ISM 6564 — Text Analytics, Fall 2026.

Week 4's seq2seq block needs a task that is (a) genuinely sequence-to-sequence,
(b) small enough to train twice inside a 12:30 class, and (c) *diagnostic* —
the failure mode has to be visible rather than statistical. Date normalisation
is the standard choice:

    "the 3rd of september , 1993"  ->  "1993-09-03"

It is diagnostic in two ways the lecture leans on:

1. **The fixed-width bottleneck.** Every input carries exactly the same amount
   of information (a day, a month, a year), but the surface forms range from
   8 to ~34 characters. A no-attention encoder-decoder must squeeze all of it
   through one fixed-size context vector, so accuracy falls off as the input
   gets longer while an attention decoder's does not. Half the formats here are
   deliberately verbose so that gap is measurable rather than theoretical.

2. **Readable alignments.** The output is monotonic-ish but *reordered*
   (YYYY-MM-DD from inputs that are usually D-M-Y), so a trained attention
   heatmap looks like a real alignment rather than a diagonal.

No real-world corpus is used: dates are drawn uniformly from 1990-01-01 to
2030-12-28 and rendered through the templates below. The generator is
deterministic given the seeds, so the committed CSVs can be rebuilt exactly:

    uv run python week-04-sequence-models/data/make_dates.py

Writes `dates_train.csv` (6,000 rows) and `dates_test.csv` (1,000 rows) next to
this file, each with columns `surface,iso`.

Licence: generated by this script; released with the course materials under the
repository's licence. No third-party data.
"""

from __future__ import annotations

import csv
import datetime as dt
import random
from pathlib import Path

HERE = Path(__file__).parent

MONTHS = [
    "january", "february", "march", "april", "may", "june",
    "july", "august", "september", "october", "november", "december",
]
WEEKDAYS = [
    "monday", "tuesday", "wednesday", "thursday",
    "friday", "saturday", "sunday",
]

# Six terse formats and six verbose ones. The verbose half is what makes the
# fixed-width-bottleneck experiment in the notebook show a real gap.
SHORT_FORMATS = [
    "{d}/{m}/{y}",
    "{y}.{m:02d}.{d:02d}",
    "{d} {ab} {y}",
    "{ab} {d} {y}",
    "{d}-{ab}-{y}",
    "{ab}. {d}, {y}",
]
LONG_FORMATS = [
    "the {d}{suf} of {mon} , {y}",
    "{wd} , {mon} {d} , {y}",
    "on {mon} the {d}{suf} , {y}",
    "{wd} the {d}{suf} of {mon} {y}",
    "dated {mon} {d} , {y} .",
    "received on {d} {mon} {y}",
]
FORMATS = SHORT_FORMATS + LONG_FORMATS

START = dt.date(1990, 1, 1)
END = dt.date(2030, 12, 28)
SPAN = (END - START).days


def ordinal_suffix(day: int) -> str:
    if 11 <= day % 100 <= 13:
        return "th"
    return {1: "st", 2: "nd", 3: "rd"}.get(day % 10, "th")


def render(date: dt.date, fmt: str) -> str:
    return fmt.format(
        d=date.day,
        m=date.month,
        y=date.year,
        ab=MONTHS[date.month - 1][:3],
        mon=MONTHS[date.month - 1],
        wd=WEEKDAYS[date.weekday()],
        suf=ordinal_suffix(date.day),
    )


def generate(n: int, seed: int) -> list[tuple[str, str]]:
    """n (surface, iso) pairs. Every format is used with equal probability."""
    rng = random.Random(seed)
    rows = []
    for _ in range(n):
        date = START + dt.timedelta(days=rng.randrange(SPAN))
        rows.append((render(date, rng.choice(FORMATS)), date.isoformat()))
    return rows


def write(rows: list[tuple[str, str]], path: Path) -> None:
    with path.open("w", newline="", encoding="utf-8") as fh:
        w = csv.writer(fh)
        w.writerow(["surface", "iso"])
        w.writerows(rows)
    lengths = [len(s) for s, _ in rows]
    print(
        f"wrote {path.name}: {len(rows):,} rows, "
        f"surface length {min(lengths)}-{max(lengths)} chars, "
        f"{path.stat().st_size / 1000:.0f} kB"
    )


def main() -> None:
    write(generate(6000, seed=6564), HERE / "dates_train.csv")
    write(generate(1000, seed=2026), HERE / "dates_test.csv")


if __name__ == "__main__":
    main()
